import { get } from "./api";

export const fetchGenreList = () => get('/genre/movie/list')
export const fetchTopRatedMovies = (params?: any) => get('/movie/top_rated', params)
export const fetchPopularMovies = (params?: any) => get('/movie/popular', params)
export const fetchNowPlayingMovies = (params?: any) => get('/movie/now_playing', params)
export const fetchUpcomingMovies = (params?: any) => get('/movie/upcoming', params)
export const fetchDiscoverMovies = (params?: any) => get('/discover/movie', params)
export const searchMovies = ( params?: any) => get('/search/movie', params)
export const fetchMoviesByGenre = (params?: any) => get('/discover/movie', params)
export const fetchMovieDetails = (movieId: string) => get(`/movie/${movieId}`)
export const fetchMovieImages = (movieId: string) => get(`/movie/${movieId}/images`)
export const fetchSimilarMovies = (movieId: string, params?: any) => get(`/movie/${movieId}/similar`, params)
export const fetchMovieCredits = (movieId: string) => get(`/movie/${movieId}/credits`)
export const fetchMovieReleaseDates = (movieId: string) => get(`/movie/${movieId}/release_dates`)
export const fetchMovieReviews = (movieId: string) => get(`/movie/${movieId}/reviews`)
export const fetchMovieWatchProviders = (movieId: string) => get(`/movie/${movieId}/watch/providers`)
export const fetchMovieVideos = (movieId: string) => get(`/movie/${movieId}/videos`)